#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit ${1}


. "$(dirname "$0")/_/husky.sh"

# 读取提交消息文件并修改 footer
MSG_FILE="$1"
TEMP_FILE="$(mktemp)"
sed 's/^\[\(.*\)$/\[\1]/' "$MSG_FILE" > "$TEMP_FILE"
mv "$TEMP_FILE" "$MSG_FILE"